### ISSUE TITLE
Task-Get errors

### ISSUE THREAD

**Issue by chevcheli0s** [ptarmiganlabs/ctrl-q#291]
### What version of Ctrl-Q are you using?

3.11.0

### What command did you use to start Ctrl-Q?

./ctrl-q task-get --host myhost --auth-user-dir domain --auth-user-id user --log-level silly

### What operating system are you using?

Debian 11

### What CPU architecture are you using?

x86_64

### What Qlik Sense versions are you using?

2023-February sp5

### Describe the Bug

Hi!
I have some errors when trying to execute tasks-get
First error with event trigger for [telemetry dashboard](https://community.qlik.com/t5/Official-Support-Articles/How-to-enable-Qlik-Sense-QIX-performance-logging-and-use-the/ta-p/1711405)
```
2023-07-19T09:24:44.750Z debug: Processing composite event "telemetry-metadata-trigger" for reload task "TelemetryDashboard-2-Reload-Dashboard" (a2e18a30-4d80-450e-aba5-ba30263d9c50)
2023-07-19T09:24:44.751Z error: GET TASK: TypeError: Cannot read properties of null (reading 'id')
    at QlikSenseTasks.getTaskModelFromQseow (/snapshot/src/build/lib/index.js)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getTask (/snapshot/src/build/lib/index.js)
```
![image](https://github.com/ptarmiganlabs/ctrl-q/assets/48658076/cf618fc5-db55-4307-b04d-5fb58441bf9e)
I think that is because trigger set to execution of external program task("TelemetryDashboard-1-Generate-Metadata")
When I delete this event trigger I receive another one error:
```
2023-07-19T09:17:48.165Z warn: Downstream task in task tree not found. From: node-3feeb6bf-a3c9-40ed-ba3b-1bbc324b8188, to: 95ce6de2-748c-4c15-9d7c-7b3a9190d515 
2023-07-19T09:17:48.529Z error: GET TASK SUBTREE: RangeError: Maximum call stack size exceeded
    at QlikSenseTasks.getTaskSubTree (/snapshot/src/build/lib/index.js)
    at QlikSenseTasks.getTaskSubTree (/snapshot/src/build/lib/index.js)
    at QlikSenseTasks.getTaskSubTree (/snapshot/src/build/lib/index.js)
    at QlikSenseTasks.getTaskSubTree (/snapshot/src/build/lib/index.js)
    at QlikSenseTasks.getTaskSubTree (/snapshot/src/build/lib/index.js)
    at QlikSenseTasks.getTaskSubTree (/snapshot/src/build/lib/index.js)
    at QlikSenseTasks.getTaskSubTree (/snapshot/src/build/lib/index.js)
    at QlikSenseTasks.getTaskSubTree (/snapshot/src/build/lib/index.js)
    at QlikSenseTasks.getTaskSubTree (/snapshot/src/build/lib/index.js)
    at QlikSenseTasks.getTaskSubTree (/snapshot/src/build/lib/index.js)
2023-07-19T09:17:48.587Z warn: Downstream task in task tree not found. From: node-800e4add-dd91-4afe-84eb-ca2b513a0025, to: c05ead75-2b02-4ce5-ab1e-673f6d02c41e 
```

**Comment by ale-novoa** [comment]
UPDATE:  after deleting the external program task that was created by the Telemetry app (TelemetryDashboard-1-Generate-Metadata) I was able to extract all of the tasks.

That was the only external program task I had in my server, so not sure if it was an issue with this specific task or with any external program task.
But it is working fine now.

**Comment by mountaindude** [comment]
Planning to look into this during coming days or so.
Most likely related to external program tasks not being properly handled, it seems. 

Thanks for good bug reports!

**Comment by mountaindude** [comment]
@ale-novoa and @chevcheli0s 

Please give [3.13.0](https://github.com/ptarmiganlabs/ctrl-q/releases) a try, it works for me here.
I could reproduce your errors, btw.

Also, note that the `--task-type` parameter has two possible values `reload` and `ext-program` that can be combined, depending on what tasks you want to include.
You probably want to include both, to get both reload tasks and external program tasks.

...and I just now found a bug when using `--task-type ext-program`. 
I.e. only including external program tasks. Duh... will fix. Shouldn't be a problem for you I think/hope.

**Comment by chevcheli0s** [comment]
I tested it
[log.zip](https://github.com/ptarmiganlabs/ctrl-q/files/12758619/log.zip)

**Comment by mountaindude** [comment]
@chevcheli0s 
Ok, so your task chain differs from the one I tested on somehow. 

Can you share what it looks like? I am particularly interested in if tasks are reload tasks/ext program tasks and how the tasks are triggered.

**Comment by chevcheli0s** [comment]
@mountaindude 
There are some examples
![image](https://github.com/ptarmiganlabs/ctrl-q/assets/48658076/04e7dc87-916f-4d07-8b54-344848492e6e)
![image](https://github.com/ptarmiganlabs/ctrl-q/assets/48658076/07becb88-36a4-436b-a4f2-06bd9642cdcf)

**Comment by mountaindude** [comment]
@chevcheli0s 
I cannot reproduce the "Maximum call stack size exceeded" error. 
How long is your reload chain (approximately)?

**Comment by chevcheli0s** [comment]
@mountaindude Maybe this can help
```
2023-10-09T10:13:12.092Z debug: Processing composite event "reports_view_order_full" for reload task "05. ***" (56baa838-2d94-47e4-9389-72cfdcfb3a9d)
2023-10-09T10:13:12.092Z debug: Current composite event triggers a reload task. Processing composite event "reports_view_order_full" for reload task "05. ***" (56baa838-2d94-47e4-9389-72cfdcfb3a9d)
2023-10-09T10:13:12.092Z verbose: Composite event "reports_view_order_full" is triggerer by 3 upstream tasks.
2023-10-09T10:13:12.092Z debug: Composite event "reports_view_order_full" is triggered by reload task with ID=c0cf4571-7d77-4e83-986a-d1b55fa26cbb.
2023-10-09T10:13:12.092Z debug: Composite event "reports_view_order_full" is triggered by reload task with ID=862d87b5-9a15-4382-b4e3-1f6901c7b6e3.
2023-10-09T10:13:12.092Z debug: Composite event "reports_view_order_full" is triggered by reload task with ID=2eb6aa9a-434e-495b-bc42-d6bffd2ef9ca.
2023-10-09T10:13:12.092Z debug: Added edge from composite event meta node "node-c4078faa-52da-4880-9fc8-741a4f63134f" to reload task ID=56baa838-2d94-47e4-9389-72cfdcfb3a9d.
2023-10-09T10:13:12.189Z warn: Downstream task in task tree not found. From: node-5f62e677-63dd-41c9-b9c4-043a84e72832, to: 95ce6de2-748c-4c15-9d7c-7b3a9190d515 
2023-10-09T10:13:12.614Z error: GET TASK SUBTREE: RangeError: Maximum call stack size exceeded
    at prepareStackTrace (node:internal/errors:116:5)
    at eb.getTaskSubTree (/snapshot/ctrl-q/build.cjs:283:18113)
    at eb.getTaskSubTree (/snapshot/ctrl-q/build.cjs:283:13850)
    at eb.getTaskSubTree (/snapshot/ctrl-q/build.cjs:283:13850)
    at eb.getTaskSubTree (/snapshot/ctrl-q/build.cjs:283:13850)
    at eb.getTaskSubTree (/snapshot/ctrl-q/build.cjs:283:13850)
    at eb.getTaskSubTree (/snapshot/ctrl-q/build.cjs:283:13850)
    at eb.getTaskSubTree (/snapshot/ctrl-q/build.cjs:283:13850)
    at eb.getTaskSubTree (/snapshot/ctrl-q/build.cjs:283:13850)
    at eb.getTaskSubTree (/snapshot/ctrl-q/build.cjs:283:13850)
2023-10-09T10:13:12.699Z warn: Downstream task in task tree not found. From: node-470d008b-d17e-4087-9afd-3b4d5d9794b1, to: c05ead75-2b02-4ce5-ab1e-673f6d02c41e 
```
![image](https://github.com/ptarmiganlabs/ctrl-q/assets/48658076/ce72cb83-f68a-4a98-aff4-dd39a693277e)
![image](https://github.com/ptarmiganlabs/ctrl-q/assets/48658076/edb9c5b9-6efc-468d-904c-d5a579276eaf)
![image](https://github.com/ptarmiganlabs/ctrl-q/assets/48658076/42df5aa4-47ee-4d3e-9c2d-44f80227cd88)

The last three tasks S* with daily triggers at 09:30 
```
(Get-QlikReloadTask).Count
1796
```

**Comment by mountaindude** [comment]
Yeah... that whole part of the tool needs a bit of restructuring, it seems. 

Recursive code (as used here) can be convenient but also pose a risk.
I've started the refactoring but it will be some time until it's ready, I am afraid.

**Comment by mountaindude** [comment]
Version 3.14 was just released (download [here](https://github.com/ptarmiganlabs/ctrl-q/releases/tag/v3.14.0)), it contains (among other things) changes related to this ticket.

**Comment by chevcheli0s** [comment]
Error still persist 

2023-11-20T08:13:21.287Z .[32minfo.[39m: -----------------------------------------------------------
2023-11-20T08:13:21.288Z .[32minfo.[39m: | Ctrl-Q
2023-11-20T08:13:21.288Z .[32minfo.[39m: |
2023-11-20T08:13:21.288Z .[32minfo.[39m: | Version      : 3.14.0
2023-11-20T08:13:21.289Z .[32minfo.[39m: | Log level    : info
2023-11-20T08:13:21.289Z .[32minfo.[39m: |
2023-11-20T08:13:21.289Z .[32minfo.[39m: | Command      : task-get
2023-11-20T08:13:21.289Z .[32minfo.[39m: |              : get info about one or more tasks
2023-11-20T08:13:21.289Z .[32minfo.[39m: |
2023-11-20T08:13:21.290Z .[32minfo.[39m: | Run Ctrl-Q with the '--help' option to see a list of all available options for this command.
2023-11-20T08:13:21.290Z .[32minfo.[39m: |
2023-11-20T08:13:21.290Z .[32minfo.[39m: | https://github.com/ptarmiganlabs/ctrl-q
2023-11-20T08:13:21.290Z .[32minfo.[39m: ----------------------------------------------------------
2023-11-20T08:13:21.291Z .[32minfo.[39m:
2023-11-20T08:13:21.416Z .[32minfo.[39m: Successfully retrieved 246 tags from QSEoW
2023-11-20T08:14:37.470Z .[31merror.[39m: GET TASK SUBTREE (tree): RangeError: Maximum call stack size exceeded
    at prepareStackTrace (node:internal/errors:116:5)
    at uw.getTaskSubTree (/snapshot/ctrl-q/build.cjs:284:16260)
    at uw.getTaskSubTree (/snapshot/ctrl-q/build.cjs:284:11990)
    at uw.getTaskSubTree (/snapshot/ctrl-q/build.cjs:284:11990)
    at uw.getTaskSubTree (/snapshot/ctrl-q/build.cjs:284:11990)
    at uw.getTaskSubTree (/snapshot/ctrl-q/build.cjs:284:11990)
    at uw.getTaskSubTree (/snapshot/ctrl-q/build.cjs:284:11990)
    at uw.getTaskSubTree (/snapshot/ctrl-q/build.cjs:284:11990)
    at uw.getTaskSubTree (/snapshot/ctrl-q/build.cjs:284:11990)
    at uw.getTaskSubTree (/snapshot/ctrl-q/build.cjs:284:11990)

**Comment by mountaindude** [comment]
Noooo....... Darn.

Will have to loop back to you on this one.
I am not able to reproduce the error here, so I need to understand what's causing it.

**Comment by mountaindude** [comment]
@chevcheli0s 
I found the likely cause of this: Circular task dependencies.
As of right now Ctrl-Q does not handle these nicely, coming in next (or next-next) version.

Getting tasks as a table (CSV or Excel or on-screen) still works, from what I can tell.

**Comment by mountaindude** [comment]
Regarding circular task trees.

Let's say we have task relations like this:

![image](https://github.com/ptarmiganlabs/ctrl-q/assets/1029262/b796caa7-648f-4e5c-b591-34383df522a5)

 
 Then the next Ctrl-Q version will create this task tree:
 
![image](https://github.com/ptarmiganlabs/ctrl-q/assets/1029262/82886b5c-9d8b-488c-b930-7563e66aef15)

Circular task trees are perfectly fine from a Qlik Sense point of view, and when visualising them in a network diagram or flowchart it's possible to route an arrow back to a previous task.

The challenge is rather the nature of the tree format. 
There we have to identify those circular relationships and break them, ideally while also clearly stating where the break occurs.
