### ISSUE TITLE
Enigma error when reading master dimensions

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/ctrl-q#314]
### What version of Ctrl-Q are you using?

3.13.1

### What command did you use to start Ctrl-Q?

See below

### What operating system are you using?

Win10

### What CPU architecture are you using?

-

### What Qlik Sense versions are you using?

2023-May-p6

### Describe the Bug

```
PS C:\tools\ctrl-q> .\ctrl-q.exe master-item-dim-get `
>> --host 192.168.100.109 `
>> --auth-user-dir LAB `
>> --auth-user-id goran `
>> --app-id a3e0f5d2-000a-464f-998d-33d333b175d7 `
>> --output-format table
2023-09-27T04:22:18.418Z info: -----------------------------------------------------------
2023-09-27T04:22:18.418Z info: | Ctrl-Q
2023-09-27T04:22:18.418Z info: |
2023-09-27T04:22:18.433Z info: | Version      : 3.13.1
2023-09-27T04:22:18.433Z info: | Log level    : info
2023-09-27T04:22:18.433Z info: |
2023-09-27T04:22:18.433Z info: | Command      : master-item-dim-get
2023-09-27T04:22:18.433Z info: |              : get info about one or more master dimensions
2023-09-27T04:22:18.433Z info: |
2023-09-27T04:22:18.433Z info: | Run Ctrl-Q with the '--help' option to see a list of all available options for this command.
2023-09-27T04:22:18.433Z info: |
2023-09-27T04:22:18.433Z info: | https://github.com/ptarmiganlabs/ctrl-q
2023-09-27T04:22:18.433Z info: ----------------------------------------------------------
2023-09-27T04:22:18.433Z info:
2023-09-27T04:22:18.433Z info: Get master dimensions
2023-09-27T04:22:18.855Z error: Error: Object not found
    at createEnigmaError (C:\snapshot\ctrl-q\node_modules\enigma.js\enigma.js:371:12)
    at Intercept.apiResponseInterceptor (C:\snapshot\ctrl-q\node_modules\enigma.js\enigma.js:1868:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async XK (C:\snapshot\ctrl-q\build.cjs:70:2851)
```

**Comment by mountaindude** [comment]
Only happens to some apps.

App id `a3e0f5d2-000a-464f-998d-33d333b175d7` causes error, while app id `2933711d-6638-41d4-a2d2-6dd2d965208b` does not.

**Comment by mountaindude** [comment]
Bug caused by Ctrl-Q trying to get  per-value colors for drill-down dimensions - but such dimensions don't support per-value colors.
