### ISSUE TITLE
Verify that certificate files exist before trying to read them

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/ctrl-q#46]
Running stand-alone binary with default cert locations gives

```bash
➜  Downloads ./ctrl-q-cli master-item-import --host 192.168.100.109 --userdir LAB --userid goran --appid 2933711d-6638-41d4-a2d2-6dd2d965208b --loglevel verbose --file ./ctrl-q-cli-testdata.xlsx --sheet Sales --col-item-type "Master item type" --col-master-item-name "Master Item Name" --col-master-item-expr "Expression" --col-master-item-tag "Tag" --col-master-item-descr "Description" --col-master-item-label "Label" --limit-import-count 5
2022-05-07T19:39:43.072Z info: Import master items from definitions in Excel file "./ctrl-q-cli-testdata.xlsx"
2022-05-07T19:39:43.095Z error: Error: File '/**/ctrl-q-cli/src/lib/cert/client_key.pem' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:614:19)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:1006:29)
    at Object.readFileSync (pkg/prelude/bootstrap.js:1054:18)
    at readCert (/snapshot/ctrl-q-cli/src/lib/enigma.js)
    at RPC.createSocket (/snapshot/ctrl-q-cli/src/lib/enigma.js)
    at RPC.open (/snapshot/ctrl-q-cli/node_modules/enigma.js/enigma.js:1485:30)
    at Session.open (/snapshot/ctrl-q-cli/node_modules/enigma.js/enigma.js:754:41)
    at importMasterItemFromExcel (/snapshot/ctrl-q-cli/src/lib/importexcel.js)
    at importMasterItemFromFile (/snapshot/ctrl-q-cli/src/lib/importexcel.js)
    at Command.<anonymous> (/snapshot/ctrl-q-cli/src/ctrl-q-cli.js)
➜  Downloads
```

**Comment by mountaindude** [comment]
Covered by #81 .
